version: '3'
services:
  twitterapi:
    image: "logantr/twitter-api:latest"

    container_name: TWITTER_API
    environment:
      - TELEGRAM_TOKEN=
      - TELEGRAM_CHAT_ID=
      - CONSUMER_KEY=
      - CONSUMER_SECRET=
      - ACCESS_TOKEN=
      - ACCESS_SECRET=
      - TWITTER_USERNAME=
      - GET_UPDATE=60
    restart: "on-failure"